version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8081:8081"
    restart: unless-stopped
    env_file:
      - .env

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    env_file:
      - .env
