version: "3.8"

services:
  # db:
  #   image: postgres:15
  #   restart: always
  #   env_file:
  #     - .env
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #     - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  #   networks:
  #     - app-network
  backend:
    build: ./backend
    ports:
      - "8081:8081"
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - app-network
  frontend:
    build: 
      context: ./frontend
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres-data:
